version: '3.1'
services:
  postgres_container:
    image: postgres:latest
    container_name: psql_container
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: mypasswd
      POSTGRES_USER: myuser
